### ISSUE TITLE
Using revolver with phylowgs outputs

### ISSUE THREAD

**Issue by elifirem** [caravagn/revolver#20]
Hi,
If I'm not wrong it seems that we can use use phylowgs trees as inputs for revolver. I went through the wiki page but am still not sure which part of outputs of phylowgs can be used and how. Could you please provide guidance on this? Also my samples are not multi-regional but I have multiple samples on different time points. Would that be a problem? Thanks a lot!
Irem

**Comment by caravagn** [comment]
Hi @elifirem,

REVOLVER can use a custom set of input trees that you have computed with PhyloWGS or any other tree-inference tool. You just need to use the `revolver_compute_phylogeny`

https://github.com/caravagn/revolver/blob/master/R/rev_cohort.R

which takes as input a list of adjacency matrices and scores (`precomputed.trees` and `precomputed.scores`). 

If I well remember PhyloWGS computes  a posterior over trees right with tree-stick breaking processes no? If so, I would use the top K trees scored by posterior likelihood (non-negative); this seems sensitive to me.

Concerning longitudinal vs cross-sectional, I've seen several papers doing that kind of analysis (subclonal deconvolution plus tree inference), thus I'd say the same assumptions of those analysis apply here. This does not seem to me an issue with the tool, and I think the real question is whether it is the best to assume the data are iid when we work with longitudinal biopsies.

Please let me know how it goes, I have never tested extensively this feature and I am curious to know if that works smooth. I will provide you with help otherwise.

Best

G

**Comment by elifirem** [comment]
Hi @caravagn,
Thanks for prompt reply. Phylowgs reports possible trees and posterior likelihoods but they are all in json format to view in html. There is smc-het challange code which takes phylowgs outputs and writes the best tree's structure in .txt but I'm guessing it won't be enough for revolver and I actually need to provide other possible trees too, right? I can write a script to extract this information but could you give a brief example of how `precomputed.trees` and `precomputed.scores` files should like (column names etc) so I can start working on this. I'll let you know how it goes. Thanks!
Irem
