### ISSUE TITLE
Input file -- where to obtain the "cluster" input column for the input data. 

### ISSUE THREAD

**Issue by xtmgah** [caravagn/revolver#21]
Hello:

For the input file format, where can I get the cluster information? Which algorithm is better to get the cluster information? is the cluster column are necessary for the input files? Thanks.

**Comment by xtmgah** [comment]
Thanks for your replay. Another question for me is should I only included "is.drive=TRUE" mutations or any mutations (including intron and intergenc region) will be used for the phylogenetic tree computing.

**Comment by caravagn** [comment]
Would you mind describing a bit what kind of study are you trying to do? Type of data, sequencing approach, research hypothesis etc. It is difficult otherwise to give sensitive answers to broad questions like this one; drivers determine the signal to pick up repeated trajectories, but according to the study it might be much more wise to use all mutation data (drivers and non-drivers).

**Comment by caravagn** [comment]
No reply. I assume this was solved.
