### ISSUE TITLE
Any suggestions with 'clonal cluster' from PyClone?

### ISSUE THREAD

**Issue by Chitanda-Satou** [caravagn/revolver#28]
Dear author, thanks a lot for developing this wonderful package!

May I have your suggestions about how to set the "clonal cluster" from PyClone's CCF result?

Such as an example below, if we plot the CCF of two samples with labels of T0/T1 from PyClone, it is really confusing which cluster is clonal. 

Thanks a lot!
![图片](https://user-images.githubusercontent.com/32410912/71574990-20f68580-2b26-11ea-868e-9aef24b6cd3b.png)

**Comment by caravagn** [comment]
Hello, if I well remember PyCLone uses the Cellular Prevalence on the plot axis, so ~100% should be the clonal cluster. Now, in a matched plot I would have expected to see some points on the diagonal of the plot -- those would have been the clonal mutations i both samples. Do you have any idea why that is not the case?

**Comment by Chitanda-Satou** [comment]
Thanks for your quick reply, @caravagn .

I fully aggree with your opinion. Unfortunately in our practice, this situation happens from time to time.  Perhaps more research has to be done to make it cleart that wheter this is induced by bad PyClone clustering or biological reasons.

1. Moreover, would you please teach me how revolver deals with this situation: two samples are completely independent and have no common source. How to give a clonal cluster to revolver's input for this?
I just draw a diagram to show one case that T1 and T2 are completely independent:
![图片](https://user-images.githubusercontent.com/32410912/71607156-f8b46880-2bb1-11ea-9b40-5b3ec3d128a5.png)

2. I wish you don't mind, can you tell me your recommended clone clustering softwares, whether it's for CCF or binary (0/1).

Thanks again!

**Comment by caravagn** [comment]
1. The clonal cluster is the set of shared mutations in T1 ad T2. They represent an ancestral lineage from which T1 and T2 evolved independently. However, If T1 and T2 started from different initial cells (phylogenetically independent tumours), they might have no shared mutation. A confounder is of course the sequencing that you do (exome I presume here), so you will never know if they shared some non-coding mutations . 

2. All of them are currently limited [(see this)](https://www.biorxiv.org/content/10.1101/586560v1) bub pyClone would do the job for you here. 

In your case, if you are convinced that T1 and T2 are tumours that originate from different cells (because they are spatially separated), then I would not make a multi-region analysis. Instead, you could input two single-biopsy samples to revolver, after running pyClone separately on each biopsy.
In that case you need to use CCF values.

**Comment by Chitanda-Satou** [comment]
Thanks a lot, Dr Caravagna.

Your advice makes things clear.

I shall close this issue.

Have a nice day.
