### ISSUE TITLE
how to prepare binary data for revolver

### ISSUE THREAD

**Issue by YunjieSong** [caravagn/revolver#32]
Can anyone tell me how to prepare the input binary file for revolver?  In FAQ,, it says “If you use binary data, you can immediately use REVOLVER. This type of data has lower-resolution compared to CCF.” ，but i don't know where to get the information for the cluster, is.clonal (input dataframe)?

**Comment by caravagn** [comment]
Hello @YunjieSong, we have a [website ](https://caravagn.github.io/revolver) that contains vignettes and examples with the tool; could you see if the section on [input formats](https://caravagn.github.io/revolver/articles/Input_formats.html) helps you prepare your data? If not I will help you myself (I would probably need a bit more information).

**Comment by YunjieSong** [comment]
Thanks, I have read the vignettes, but there are several things I don't understand. 1) I have generated CCF values for SNVs using pyClone, but i don't know how to correlate the CNV results (from cnvkit) to SNVs cluster. In particular, how to assign cluster id of SNV to  CNV? how to calculate the CCF of CNV?   2) how to draw the repeated trajectories for a specific cluster (similar to Fig3b in the article)?

**Comment by caravagn** [comment]
1) is all about assigning CCF values to CNVs. I am not a user of CNVKit, but If you have used a caller that calls only clonal CNVs, then all CCF values are 1. Otherwise, if you have used a caller that supports subclonal CNVs like Battemberg, then the caller should output the segment's CCF (by definition). Whatever the CCF values, you can assign them to you clusters post-hoc, if you cannot include them in your favourite CCF-based clustering model (eg pyClone); note that some tools like pyClone already use CNV data to compute CCF, so you do not have to do much about that. 2) Fig 3b in the paper was manually curated starting from the output of [plot_drivers_graph](https://caravagn.github.io/revolver/reference/plot_drivers_graph.html); the function has parameters to subset the drivers to draw etc.

**Comment by YunjieSong** [comment]
thank you very much.
