### ISSUE TITLE
How to assign cluster id to samples if using binary data? 

### ISSUE THREAD

**Issue by sunandinisharma** [caravagn/revolver#45]
I am using the binary input data for REVOLVER. Not sure how to assign the cluster id to patients? In my case, I am not using PyClone as I have Copy number information available and want to keep everything in binary format. Can I get some explanation about how to assign patients into clusters while preparing the input? Is it necessary to use the sub-clonal deconvolution using Pyclone or other tolls?

**Comment by caravagn** [comment]
Hi @sunandinisharma,

Say you have samples A, B and C in a patient, with 3 CNAs (X, Y and Z) observed

```
   A | B | C
X: 1 | 1 | 1
Y: 1 | 1 | 1
Z: 0 | 1 | 0
```

you clusters should be 2, one for X and Y, and one only for Z. This is because the rows are identical among and X and Y, and are different from the ones in Z. 

The cluster label obviously does not matter.
